export default {
  "list": [{
    "id": 1,
    "name": "森林动物",
    "img": "/daohangtubiao/sldw.png",
    "cardList": [{
      "id": 1,
      "name": "Elephant",
      "img": "/img2/forestanimal/elephant.png",
      "audioUrl": "/audio3/word/forestanimal/elephant.mp3"
    }, {
      "id": 2,
      "name": "Zebra",
      "img": "/img2/forestanimal/zebra.png",
      "audioUrl": "/audio3/word/forestanimal/zebra.mp3"
    }, {
      "id": 3,
      "name": "Bear",
      "img": "/img2/forestanimal/beer.png",
      "audioUrl": "/audio3/word/forestanimal/bear.mp3"
    }, {
      "id": 4,
      "name": "Panda",
      "img": "/img2/forestanimal/panda.png",
      "audioUrl": "/audio3/word/forestanimal/panda.mp3"
    }, {
      "id": 5,
      "name": "Lion",
      "img": "/img2/forestanimal/lion.png",
      "audioUrl": "/audio3/word/forestanimal/lion.mp3"
    }, {
      "id": 6,
      "name": "Wolf",
      "img": "/img2/forestanimal/wolf.png",
      "audioUrl": "/audio3/word/forestanimal/wolf.mp3"
    }, {
      "id": 7,
      "name": "Pig",
      "img": "/img2/forestanimal/pig.png",
      "audioUrl": "/audio3/word/forestanimal/pig.mp3"
    }, {
      "id": 8,
      "name": "Tiger",
      "img": "/img2/forestanimal/tiger.png",
      "audioUrl": "/audio3/word/forestanimal/tiger.mp3"
    }, {
      "id": 9,
      "name": "Eagle",
      "img": "/img2/forestanimal/eagle.png",
      "audioUrl": "/audio3/word/forestanimal/eagle.mp3"
    }, {
      "id": 10,
      "name": "Snake",
      "img": "/img2/forestanimal/snake.png",
      "audioUrl": "/audio3/word/forestanimal/snake.mp3"
    }, {
      "id": 11,
      "name": "Horse",
      "img": "/img2/forestanimal/horse.png",
      "audioUrl": "/audio3/word/forestanimal/horse.mp3"
    }, {
      "id": 12,
      "name": "Camel",
      "img": "/img2/forestanimal/camel.png",
      "audioUrl": "/audio3/word/forestanimal/camel.mp3"
    }, {
      "id": 13,
      "name": "Deer",
      "img": "/img2/forestanimal/deer.png",
      "audioUrl": "/audio3/word/forestanimal/deer.mp3"
    }]
  }, {
    "id": 2,
    "name": "交通工具",
    "img": "/daohangtubiao/jtgj.png",
    "cardList": [{
      "id": 14,
      "name": "Airplane",
      "img": "/img2/vehicle/airplane.png",
      "audioUrl": "/audio3/word/vehicle/airplane.mp3"
    }, {
      "id": 15,
      "name": "Bike",
      "img": "/img2/vehicle/bike.png",
      "audioUrl": "/audio3/word/vehicle/bike.mp3"
    }, {
      "id": 16,
      "name": "Boat",
      "img": "/img2/vehicle/boat.png",
      "audioUrl": "/audio3/word/vehicle/boat.mp3"
    }, {
      "id": 17,
      "name": "Bus",
      "img": "/img2/vehicle/bus.png",
      "audioUrl": "/audio3/word/vehicle/bus.mp3"
    }, {
      "id": 18,
      "name": "Car",
      "img": "/img2/vehicle/car.png",
      "audioUrl": "/audio3/word/vehicle/car.mp3"
    }, {
      "id": 19,
      "name": "Hellicopter",
      "img": "/img2/vehicle/helicopter.png",
      "audioUrl": "/audio3/word/vehicle/helicopter.mp3"
    }, {
      "id": 20,
      "name": "Jet",
      "img": "/img2/vehicle/jet.png",
      "audioUrl": "/audio3/word/vehicle/jet.mp3"
    }, {
      "id": 21,
      "name": "Locomotive",
      "img": "/img2/vehicle/locomotive.png",
      "audioUrl": "/audio3/word/vehicle/locomotive.mp3"
    }, {
      "id": 22,
      "name": "Motorcycle",
      "img": "/img2/vehicle/motorcycle.png",
      "audioUrl": "/audio3/word/vehicle/motorcycle.mp3"
    }, {
      "id": 23,
      "name": "Ship",
      "img": "/img2/vehicle/ship.png",
      "audioUrl": "/audio3/word/vehicle/ship.mp3"
    }, {
      "id": 24,
      "name": "Spaceship",
      "img": "/img2/vehicle/spaceship.png",
      "audioUrl": "/audio3/word/vehicle/spaceship.mp3"
    }, {
      "id": 112,
      "name": "Subway",
      "img": "/img2/vehicle/subway.png",
      "audioUrl": "/audio3/word/vehicle/subway.mp3"
    }, {
      "id": 25,
      "name": "Taxi",
      "img": "/img2/vehicle/taxi.png",
      "audioUrl": "/audio3/word/vehicle/taxi.mp3"
    }, {
      "id": 26,
      "name": "Train",
      "img": "/img2/vehicle/train.png",
      "audioUrl": "/audio3/word/vehicle/train.mp3"
    }, {
      "id": 27,
      "name": "Truck",
      "img": "/img2/vehicle/truck.png",
      "audioUrl": "/audio3/word/vehicle/truck.mp3"
    }, {
      "id": 28,
      "name": "Van",
      "img": "/img2/vehicle/van.png",
      "audioUrl": "/audio3/word/vehicle/van.mp3"
    }, {
      "id": 29,
      "name": "Warship",
      "img": "/img2/vehicle/warship.png",
      "audioUrl": "/audio3/word/vehicle/warship.mp3"
    }]
  }, {
    "id": 11,
    "name": "家人",
    "img": "/daohangtubiao/family.png",
    "cardList": [{
      "id": 115,
      "name": "dad",
      "img": "/img2/family/dad.png",
      "audioUrl": "/audio3/word/family/dad.mp3"
    }, {
      "id": 116,
      "name": "mom",
      "img": "/img2/family/mom.png",
      "audioUrl": "/audio3/word/family/mom.mp3"
    }, {
      "id": 117,
      "name": "big brother",
      "img": "/img2/family/big brother.png",
      "audioUrl": "/audio3/word/family/big brother.mp3"
    }, {
      "id": 118,
      "name": "big sister",
      "img": "/img2/family/big sister.png",
      "audioUrl": "/audio3/word/family/big sister.mp3"
    }, {
      "id": 119,
      "name": "little brother",
      "img": "/img2/family/little brother.png",
      "audioUrl": "/audio3/word/family/littele brother.mp3"
    }, {
      "id": 120,
      "name": "little sister",
      "img": "/img2/family/little sister.png",
      "audioUrl": "/audio3/word/family/little sister.mp3"
    }, {
      "id": 121,
      "name": "baby",
      "img": "/img2/family/baby.png",
      "audioUrl": "/audio3/word/family/baby.mp3"
    }, {
      "id": 122,
      "name": "aunt",
      "img": "/img2/family/aunt.png",
      "audioUrl": "/audio3/word/family/aunt.mp3"
    }, {
      "id": 123,
      "name": "uncle",
      "img": "/img2/family/uncle.png",
      "audioUrl": "/audio3/word/family/uncle.mp3"
    }, {
      "id": 124,
      "name": "grandma",
      "img": "/img2/family/grandma.png",
      "audioUrl": "/audio3/word/family/grandma.mp3"
    }, {
      "id": 125,
      "name": "grandpa",
      "img": "/img2/family/grandpa.png",
      "audioUrl": "/audio3/word/family/grandpa.mp3"
    }, {
      "id": 126,
      "name": "boy",
      "img": "/img2/family/boy.png",
      "audioUrl": "/audio3/word/family/boy.mp3"
    }, {
      "id": 127,
      "name": "girl",
      "img": "/img2/family/girl.png",
      "audioUrl": "/audio3/word/family/girl.mp3"
    }]
  }, {
    "id": 3,
    "name": "昆虫",
    "img": "/daohangtubiao/kc.png",
    "cardList": [{
      "id": 30,
      "name": "Ant",
      "img": "/img2/insect/ant.png",
      "audioUrl": "/audio3/word/insect/ant.mp3"
    }, {
      "id": 31,
      "name": "Cricket",
      "img": "/img2/insect/cricket.png",
      "audioUrl": "/audio3/word/insect/cricket.mp3"
    }, {
      "id": 128,
      "name": "Bee",
      "img": "/img2/insect/bee.png",
      "audioUrl": "/audio3/word/insect/bee.mp3"
    }, {
      "id": 32,
      "name": "Butterfly",
      "img": "/img2/insect/butterfly.png",
      "audioUrl": "/audio3/word/insect/butterfly.mp3"
    }, {
      "id": 33,
      "name": "Dragonfly",
      "img": "/img2/insect/dragonfly.png",
      "audioUrl": "/audio3/word/insect/dragonfly.mp3"
    }, {
      "id": 34,
      "name": "Flea",
      "img": "/img2/insect/flea.png",
      "audioUrl": "/audio3/word/insect/flea.mp3"
    }, {
      "id": 35,
      "name": "Ladybird",
      "img": "/img2/insect/ladybird.png",
      "audioUrl": "/audio3/word/insect/ladybird.mp3"
    }, {
      "id": 36,
      "name": "Mantis",
      "img": "/img2/insect/mantis.png",
      "audioUrl": "/audio3/word/insect/mantis.mp3"
    }, {
      "id": 37,
      "name": "Mosquito",
      "img": "/img2/insect/mosquito.png",
      "audioUrl": "/audio3/word/insect/mosquito.mp3"
    }, {
      "id": 38,
      "name": "Spider",
      "img": "/img2/insect/spider.png",
      "audioUrl": "/audio3/word/insect/spider.mp3"
    }]
  }, {
    "id": 4,
    "name": "小动物",
    "img": "/daohangtubiao/bird.png",
    "cardList": [{
      "id": 39,
      "name": "Bat",
      "img": "/img2/littleanimal/bat.png",
      "audioUrl": "/audio3/word/littleanimal/bat.mp3"
    }, {
      "id": 40,
      "name": "Bird",
      "img": "/img2/littleanimal/bird.png",
      "audioUrl": "/audio3/word/littleanimal/bird.mp3"
    }, {
      "id": 41,
      "name": "Cat",
      "img": "/img2/littleanimal/cat.png",
      "audioUrl": "/audio3/word/littleanimal/cat.mp3"
    }, {
      "id": 42,
      "name": "Chicken",
      "img": "/img2/littleanimal/chicken.png",
      "audioUrl": "/audio3/word/littleanimal/chicken.mp3"
    }, {
      "id": 43,
      "name": "Dog",
      "img": "/img2/littleanimal/dog.png",
      "audioUrl": "/audio3/word/littleanimal/dog.mp3"
    }, {
      "id": 44,
      "name": "Duck",
      "img": "/img2/littleanimal/duck.png",
      "audioUrl": "/audio3/word/littleanimal/duck.mp3"
    }, {
      "id": 45,
      "name": "Fox",
      "img": "/img2/littleanimal/fox.png",
      "audioUrl": "/audio3/word/littleanimal/fox.mp3"
    }, {
      "id": 46,
      "name": "Monkey",
      "img": "/img2/littleanimal/monkey.png",
      "audioUrl": "/audio3/word/littleanimal/monkey.mp3"
    }, {
      "id": 47,
      "name": "Owl",
      "img": "/img2/littleanimal/owl.png",
      "audioUrl": "/audio3/word/littleanimal/owl.mp3"
    }, {
      "id": 48,
      "name": "Rabbit",
      "img": "/img2/littleanimal/rabbit.png",
      "audioUrl": "/audio3/word/littleanimal/rabbit.mp3"
    }, {
      "id": 49,
      "name": "Rat",
      "img": "/img2/littleanimal/rat.png",
      "audioUrl": "/audio3/word/littleanimal/rat.mp3"
    }, {
      "id": 50,
      "name": "Sheep",
      "img": "/img2/littleanimal/sheep.png",
      "audioUrl": "/audio3/word/littleanimal/sheep.mp3"
    }]
  }, {
    "id": 5,
    "name": "水果",
    "img": "/daohangtubiao/fruit.png",
    "cardList": [{
      "id": 51,
      "name": "Apple",
      "img": "/img2/fruit/apple.png",
      "audioUrl": "/audio3/word/fruit/apple.mp3"
    }, {
      "id": 52,
      "name": "Banana",
      "img": "/img2/fruit/banana.png",
      "audioUrl": "/audio3/word/fruit/banana.mp3"
    }, {
      "id": 53,
      "name": "Blueberry",
      "img": "/img2/fruit/bluebeery.png",
      "audioUrl": "/audio3/word/fruit/blueberry.mp3"
    }, {
      "id": 54,
      "name": "Coconut",
      "img": "/img2/fruit/coconut.png",
      "audioUrl": "/audio3/word/fruit/coconut.mp3"
    }, {
      "id": 55,
      "name": "Durian",
      "img": "/img2/fruit/durian.png",
      "audioUrl": "/audio3/word/fruit/durian.mp3"
    }, {
      "id": 56,
      "name": "Grape",
      "img": "/img2/fruit/grape.png",
      "audioUrl": "/audio3/word/fruit/grape.mp3"
    }, {
      "id": 57,
      "name": "Haw",
      "img": "/img2/fruit/haw.png",
      "audioUrl": "/audio3/word/fruit/haw.mp3"
    }, {
      "id": 58,
      "name": "Kiwi",
      "img": "/img2/fruit/kiwi.png",
      "audioUrl": "/audio3/word/fruit/kiwi.mp3"
    }, {
      "id": 59,
      "name": "Lemon",
      "img": "/img2/fruit/lemon.png",
      "audioUrl": "/audio3/word/fruit/lemon.mp3"
    }, {
      "id": 60,
      "name": "Litchi",
      "img": "/img2/fruit/litchi.png",
      "audioUrl": "/audio3/word/fruit/litchi.mp3"
    }, {
      "id": 61,
      "name": "Mango",
      "img": "/img2/fruit/mango.png",
      "audioUrl": "/audio3/word/fruit/mango.mp3"
    }, {
      "id": 62,
      "name": "Peach",
      "img": "/img2/fruit/peach.png",
      "audioUrl": "/audio3/word/fruit/peach.mp3"
    }, {
      "id": 63,
      "name": "Watermelon",
      "img": "/img2/fruit/watermelon.png",
      "audioUrl": "/audio3/word/fruit/watermelon.mp3"
    }]
  }, {
    "id": 6,
    "name": "衣服",
    "img": "/daohangtubiao/yf.png",
    "cardList": [{
      "id": 64,
      "name": "T-shirt",
      "img": "/img2/clothes/T-shirt.png",
      "audioUrl": "/audio3/word/clothes/T-shirt.mp3"
    }, {
      "id": 65,
      "name": "Coat",
      "img": "/img2/clothes/coat.png",
      "audioUrl": "/audio3/word/clothes/coat.mp3"
    }, {
      "id": 66,
      "name": "Dress",
      "img": "/img2/clothes/dress.png",
      "audioUrl": "/audio3/word/clothes/dress.mp3"
    }, {
      "id": 67,
      "name": "Gloves",
      "img": "/img2/clothes/gloves.png",
      "audioUrl": "/audio3/word/clothes/gloves.mp3"
    }, {
      "id": 68,
      "name": "Hat",
      "img": "/img2/clothes/hat.png",
      "audioUrl": "/audio3/word/clothes/hat.mp3"
    }, {
      "id": 69,
      "name": "Scarf",
      "img": "/img2/clothes/scarf.png",
      "audioUrl": "/audio3/word/clothes/scarf.mp3"
    }, {
      "id": 70,
      "name": "Shirt",
      "img": "/img2/clothes/shirt.png",
      "audioUrl": "/audio3/word/clothes/shirt.mp3"
    }, {
      "id": 71,
      "name": "Socks",
      "img": "/img2/clothes/socks.png",
      "audioUrl": "/audio3/word/clothes/socks.mp3"
    }, {
      "id": 72,
      "name": "Sweater",
      "img": "/img2/clothes/sweater.png",
      "audioUrl": "/audio3/word/clothes/sweater.mp3"
    }, {
      "id": 73,
      "name": "Trousers",
      "img": "/img2/clothes/trousers.png",
      "audioUrl": "/audio3/word/clothes/trousers.mp3"
    }, {
      "id": 74,
      "name": "Vest",
      "img": "/img2/clothes/vest.png",
      "audioUrl": "/audio3/word/clothes/vest.mp3"
    }]
  }, {
    "id": 7,
    "name": "蔬菜",
    "img": "/daohangtubiao/vegetable.png",
    "cardList": [{
      "id": 75,
      "name": "Bean",
      "img": "/img2/vegetable/bean.png",
      "audioUrl": "/audio3/word/vegetable/bean.mp3"
    }, {
      "id": 76,
      "name": "Carrot",
      "img": "/img2/vegetable/carrot.png",
      "audioUrl": "/audio3/word/vegetable/carrot.mp3"
    }, {
      "id": 77,
      "name": "Chives",
      "img": "/img2/vegetable/chive.png",
      "audioUrl": "/audio3/word/vegetable/chive.mp3"
    }, {
      "id": 78,
      "name": "Corn",
      "img": "/img2/vegetable/corn.png",
      "audioUrl": "/audio3/word/vegetable/corn.mp3"
    }, {
      "id": 79,
      "name": "Green pepper",
      "img": "/img2/vegetable/green pepper.png",
      "audioUrl": "/audio3/word/vegetable/greenpepper.mp3"
    }, {
      "id": 80,
      "name": "Mushroom",
      "img": "/img2/vegetable/mashroom.png",
      "audioUrl": "/audio3/word/vegetable/mushroom.mp3"
    }, {
      "id": 81,
      "name": "Onion",
      "img": "/img2/vegetable/onion.png",
      "audioUrl": "/audio3/word/vegetable/onion.mp3"
    }, {
      "id": 82,
      "name": "Tomato",
      "img": "/img2/vegetable/tomato.png",
      "audioUrl": "/audio3/word/vegetable/tomato.mp3"
    }, {
      "id": 129,
      "name": "Potato",
      "img": "/img2/vegetable/patato.png",
      "audioUrl": "/audio3/word/vegetable/potato.mp3"
    }]
  }, {
    "id": 8,
    "name": "感觉",
    "img": "/daohangtubiao/feel.png",
    "cardList": [{
      "id": 83,
      "name": "angry",
      "img": "/img2/feeling/angry.png",
      "audioUrl": "/audio3/word/feeling/angry.mp3"
    }, {
      "id": 130,
      "name": "cold",
      "img": "/img2/feeling/cold.png",
      "audioUrl": "/audio3/word/feeling/cold.mp3"
    }, {
      "id": 84,
      "name": "excited",
      "img": "/img2/feeling/excited.png",
      "audioUrl": "/audio3/word/feeling/excited.mp3"
    }, {
      "id": 85,
      "name": "happy",
      "img": "/img2/feeling/happy.png",
      "audioUrl": "/audio3/word/feeling/happy.mp3"
    }, {
      "id": 86,
      "name": "hungry",
      "img": "/img2/feeling/hungry.png",
      "audioUrl": "/audio3/word/feeling/hungry.mp3"
    }, {
      "id": 87,
      "name": "sad",
      "img": "/img2/feeling/sad.png",
      "audioUrl": "/audio3/word/feeling/sad.mp3"
    }, {
      "id": 88,
      "name": "sleepy",
      "img": "/img2/feeling/sleepy.png",
      "audioUrl": "/audio3/word/feeling/sleepy.mp3"
    }, {
      "id": 89,
      "name": "surprised",
      "img": "/img2/feeling/surprised.png",
      "audioUrl": "/audio3/word/feeling/surprised.mp3"
    }, {
      "id": 90,
      "name": "warm",
      "img": "/img2/feeling/warm.png",
      "audioUrl": "/audio3/word/feeling/warm.mp3"
    }]
  }, {
    "id": 12,
    "name": "动作",
    "img": "/daohangtubiao/dz.png",
    "cardList": [{
      "id": 152,
      "name": "build",
      "img": "/img2/action/build.png",
      "audioUrl": "/audio3/word/action/build.mp3"
    }, {
      "id": 153,
      "name": "climb",
      "img": "/img2/action/climb.png",
      "audioUrl": "/audio3/word/action/climb.mp3"
    }, {
      "id": 154,
      "name": "dance",
      "img": "/img2/action/dance.png",
      "audioUrl": "/audio3/word/action/dance.mp3"
    }, {
      "id": 155,
      "name": "drink",
      "img": "/img2/action/drink.png",
      "audioUrl": "/audio3/word/action/drink.mp3"
    }, {
      "id": 156,
      "name": "eat",
      "img": "/img2/action/eat.png",
      "audioUrl": "/audio3/word/action/eat.mp3"
    }, {
      "id": 131,
      "name": "fold",
      "img": "/img2/action/fold.png",
      "audioUrl": "/audio3/word/action/fold.mp3"
    }, {
      "id": 132,
      "name": "hug",
      "img": "/img2/action/hug.png",
      "audioUrl": "/audio3/word/action/hug.mp3"
    }, {
      "id": 133,
      "name": "jump",
      "img": "/img2/action/jump.png",
      "audioUrl": "/audio3/word/action/jump.mp3"
    }, {
      "id": 134,
      "name": "kick",
      "img": "/img2/action/kick.png",
      "audioUrl": "/audio3/word/action/kick.mp3"
    }, {
      "id": 135,
      "name": "listen",
      "img": "/img2/action/listen.png",
      "audioUrl": "/audio3/word/action/listen.mp3"
    }, {
      "id": 136,
      "name": "paint",
      "img": "/img2/action/paint.png",
      "audioUrl": "/audio3/word/action/paint.mp3"
    }, {
      "id": 137,
      "name": "play",
      "img": "/img2/action/play.png",
      "audioUrl": "/audio3/word/action/play.mp3"
    }, {
      "id": 138,
      "name": "read",
      "img": "/img2/action/read.png",
      "audioUrl": "/audio3/word/action/read.mp3"
    }, {
      "id": 139,
      "name": "ride",
      "img": "/img2/action/ride.png",
      "audioUrl": "/audio3/word/action/ride.mp3"
    }, {
      "id": 140,
      "name": "run",
      "img": "/img2/action/run.png",
      "audioUrl": "/audio3/word/action/run.mp3"
    }, {
      "id": 141,
      "name": "see",
      "img": "/img2/action/see.png",
      "audioUrl": "/audio3/word/action/see.mp3"
    }, {
      "id": 142,
      "name": "sing",
      "img": "/img2/action/sing.png",
      "audioUrl": "/audio3/word/action/sing.mp3"
    }, {
      "id": 143,
      "name": "sleep",
      "img": "/img2/action/sleep.png",
      "audioUrl": "/audio3/word/action/sleep.mp3"
    }, {
      "id": 144,
      "name": "smell",
      "img": "/img2/action/smell.png",
      "audioUrl": "/audio3/word/action/smell.mp3"
    }, {
      "id": 157,
      "name": "smile",
      "img": "/img2/action/smile.png",
      "audioUrl": "/audio3/word/action/smile.mp3"
    }, {
      "id": 145,
      "name": "swim",
      "img": "/img2/action/swim.png",
      "audioUrl": "/audio3/word/action/swim.mp3"
    }, {
      "id": 146,
      "name": "swing",
      "img": "/img2/action/swing.png",
      "audioUrl": "/audio3/word/action/swing.mp3"
    }, {
      "id": 147,
      "name": "throw",
      "img": "/img2/action/throw.png",
      "audioUrl": "/audio3/word/action/throw.mp3"
    }, {
      "id": 148,
      "name": "touch",
      "img": "/img2/action/touch.png",
      "audioUrl": "/audio3/word/action/touch.mp3"
    }, {
      "id": 149,
      "name": "wash",
      "img": "/img2/action/wash.png",
      "audioUrl": "/audio3/word/action/wash.mp3"
    }, {
      "id": 150,
      "name": "wear",
      "img": "/img2/action/wear.png",
      "audioUrl": "/audio3/word/action/wear.mp3"
    }, {
      "id": 151,
      "name": "write",
      "img": "/img2/action/write.png",
      "audioUrl": "/audio3/word/action/write.mp3"
    }]
  }, {
    "id": 13,
    "name": "身体部位",
    "img": "/daohangtubiao/stbw.png",
    "cardList": [{
      "id": 158,
      "name": "arm",
      "img": "/img2/bodypart/arm.png",
      "audioUrl": "/audio3/word/bodypart/arm.mp3"
    }, {
      "id": 159,
      "name": "back",
      "img": "/img2/bodypart/back.png",
      "audioUrl": "/audio3/word/bodypart/back.mp3"
    }, {
      "id": 160,
      "name": "belly",
      "img": "/img2/bodypart/belly.png",
      "audioUrl": "/audio3/word/bodypart/belly.mp3"
    }, {
      "id": 161,
      "name": "bottom",
      "img": "/img2/bodypart/bottom.png",
      "audioUrl": "/audio3/word/bodypart/bottom.mp3"
    }, {
      "id": 162,
      "name": "chin",
      "img": "/img2/bodypart/chin.png",
      "audioUrl": "/audio3/word/bodypart/chin.mp3"
    }, {
      "id": 163,
      "name": "ear",
      "img": "/img2/bodypart/ear.png",
      "audioUrl": "/audio3/word/bodypart/ear.mp3"
    }, {
      "id": 164,
      "name": "eyebrow",
      "img": "/img2/bodypart/eyebrow.png",
      "audioUrl": "/audio3/word/bodypart/eyebrow.mp3"
    }, {
      "id": 165,
      "name": "face",
      "img": "/img2/bodypart/face.png",
      "audioUrl": "/audio3/word/bodypart/face.mp3"
    }, {
      "id": 166,
      "name": "fingers",
      "img": "/img2/bodypart/fingers.png",
      "audioUrl": "/audio3/word/bodypart/fingers.mp3"
    }, {
      "id": 167,
      "name": "foot",
      "img": "/img2/bodypart/foot.png",
      "audioUrl": "/audio3/word/bodypart/foot.mp3"
    }, {
      "id": 168,
      "name": "hair",
      "img": "/img2/bodypart/hair.png",
      "audioUrl": "/audio3/word/bodypart/hair.mp3"
    }, {
      "id": 169,
      "name": "hand",
      "img": "/img2/bodypart/hand.png",
      "audioUrl": "/audio3/word/bodypart/hand.mp3"
    }, {
      "id": 170,
      "name": "head",
      "img": "/img2/bodypart/head.png",
      "audioUrl": "/audio3/word/bodypart/head.mp3"
    }, {
      "id": 171,
      "name": "knee",
      "img": "/img2/bodypart/knee.png",
      "audioUrl": "/audio3/word/bodypart/knee.mp3"
    }, {
      "id": 172,
      "name": "leg",
      "img": "/img2/bodypart/leg.png",
      "audioUrl": "/audio3/word/bodypart/leg.mp3"
    }, {
      "id": 173,
      "name": "mouth",
      "img": "/img2/bodypart/mouth.png",
      "audioUrl": "/audio3/word/bodypart/mouth.mp3"
    }, {
      "id": 174,
      "name": "neck",
      "img": "/img2/bodypart/neck.png",
      "audioUrl": "/audio3/word/bodypart/neck.mp3"
    }, {
      "id": 175,
      "name": "nose",
      "img": "/img2/bodypart/nose.png",
      "audioUrl": "/audio3/word/bodypart/nose.mp3"
    }, {
      "id": 176,
      "name": "teeth",
      "img": "/img2/bodypart/teeth.png",
      "audioUrl": "/audio3/word/bodypart/teeth.mp3"
    }, {
      "id": 177,
      "name": "toes",
      "img": "/img2/bodypart/toes.png",
      "audioUrl": "/audio3/word/bodypart/toes.mp3"
    }, {
      "id": 178,
      "name": "tongue",
      "img": "/img2/bodypart/tongue.png",
      "audioUrl": "/audio3/word/bodypart/tongue.mp3"
    }]
  }, {
    "id": 16,
    "name": "生活用品",
    "img": "/daohangtubiao/shyp.png",
    "cardList": [{
      "id": 207,
      "name": "bathtub",
      "img": "/img2/tool/bathtub.png",
      "audioUrl": "/audio3/word/tool/bathtub.mp3"
    }, {
      "id": 208,
      "name": "clock",
      "img": "/img2/tool/clock.png",
      "audioUrl": "/audio3/word/tool/clock.mp3"
    }, {
      "id": 209,
      "name": "comb",
      "img": "/img2/tool/comb.png",
      "audioUrl": "/audio3/word/tool/comb.mp3"
    }, {
      "id": 210,
      "name": "curtain",
      "img": "/img2/tool/curtain.png",
      "audioUrl": "/audio3/word/tool/curtain.mp3"
    }, {
      "id": 211,
      "name": "lamp",
      "img": "/img2/tool/lamp.png",
      "audioUrl": "/audio3/word/tool/lamp.mp3"
    }, {
      "id": 212,
      "name": "mirror",
      "img": "/img2/tool/mirror.png",
      "audioUrl": "/audio3/word/tool/mirror.mp3"
    }, {
      "id": 213,
      "name": "mop",
      "img": "/img2/tool/mop.png",
      "audioUrl": "/audio3/word/tool/mop.mp3"
    }, {
      "id": 214,
      "name": "pillow",
      "img": "/img2/tool/pillow.png",
      "audioUrl": "/audio3/word/tool/pillow.mp3"
    }, {
      "id": 215,
      "name": "shower",
      "img": "/img2/tool/shower.png",
      "audioUrl": "/audio3/word/tool/shower.mp3"
    }, {
      "id": 216,
      "name": "soap",
      "img": "/img2/tool/soap.png",
      "audioUrl": "/audio3/word/tool/soap.mp3"
    }, {
      "id": 217,
      "name": "sponge",
      "img": "/img2/tool/sponge.png",
      "audioUrl": "/audio3/word/tool/sponge.mp3"
    }, {
      "id": 218,
      "name": "toilet",
      "img": "/img2/tool/toilet.png",
      "audioUrl": "/audio3/word/tool/toilet.mp3"
    }, {
      "id": 219,
      "name": "toothbrush",
      "img": "/img2/tool/toothbrush.png",
      "audioUrl": "/audio3/word/tool/toothbrush.mp3"
    }, {
      "id": 220,
      "name": "toothpaste",
      "img": "/img2/tool/toothpaste.png",
      "audioUrl": "/audio3/word/tool/toothpaste.mp3"
    }, {
      "id": 221,
      "name": "towel",
      "img": "/img2/tool/towel.png",
      "audioUrl": "/audio3/word/tool/towel.mp3"
    }, {
      "id": 222,
      "name": "vase",
      "img": "/img2/tool/vase.png",
      "audioUrl": "/audio3/word/tool/vase.mp3"
    }]
  }, {
    "id": 9,
    "name": "学习用品",
    "img": "/daohangtubiao/sty.png",
    "cardList": [{
      "id": 91,
      "name": "bacapack",
      "img": "/img2/study/backpack.png",
      "audioUrl": "/audio3/word/study/backpack.mp3"
    }, {
      "id": 92,
      "name": "book",
      "img": "/img2/study/book.png",
      "audioUrl": "/audio3/word/study/book.mp3"
    }, {
      "id": 93,
      "name": "crayon",
      "img": "/img2/study/crayon.png",
      "audioUrl": "/audio3/word/study/crayon.mp3"
    }, {
      "id": 94,
      "name": "eraser",
      "img": "/img2/study/eraser.png",
      "audioUrl": "/audio3/word/study/eraser.mp3"
    }, {
      "id": 95,
      "name": "glue",
      "img": "/img2/study/glue.png",
      "audioUrl": "/audio3/word/study/glue.mp3"
    }, {
      "id": 96,
      "name": "ink",
      "img": "/img2/study/ink.png",
      "audioUrl": "/audio3/word/study/ink.mp3"
    }, {
      "id": 97,
      "name": "notebook",
      "img": "/img2/study/notebook.png",
      "audioUrl": "/audio3/word/study/notebook.mp3"
    }, {
      "id": 98,
      "name": "paper",
      "img": "/img2/study/paper.png",
      "audioUrl": "/audio3/word/study/paper.mp3"
    }, {
      "id": 99,
      "name": "pencil",
      "img": "/img2/study/pencil.png",
      "audioUrl": "/audio3/word/study/pencil.mp3"
    }, {
      "id": 100,
      "name": "ruler",
      "img": "/img2/study/ruler.png",
      "audioUrl": "/audio3/word/study/ruler.mp3"
    }, {
      "id": 101,
      "name": "scissor",
      "img": "/img2/study/scissors.png",
      "audioUrl": "/audio3/word/study/scissors.mp3"
    }]
  }, {
    "id": 14,
    "name": "颜色",
    "img": "/daohangtubiao/color.png",
    "cardList": [{
      "id": 179,
      "name": "black",
      "img": "/img2/colors/black.png",
      "audioUrl": "/audio3/word/color/black.mp3"
    }, {
      "id": 180,
      "name": "blue",
      "img": "/img2/colors/blue.png",
      "audioUrl": "/audio3/word/color/blue.mp3"
    }, {
      "id": 181,
      "name": "brown",
      "img": "/img2/colors/brown.png",
      "audioUrl": "/audio3/word/color/brown.mp3"
    }, {
      "id": 182,
      "name": "dark blue",
      "img": "/img2/colors/dark blue.png",
      "audioUrl": "/audio3/word/color/dark blue.mp3"
    }, {
      "id": 183,
      "name": "gold",
      "img": "/img2/colors/gold.png",
      "audioUrl": "/audio3/word/color/gold.mp3"
    }, {
      "id": 184,
      "name": "green",
      "img": "/img2/colors/green.png",
      "audioUrl": "/audio3/word/color/green.mp3"
    }, {
      "id": 185,
      "name": "grey",
      "img": "/img2/colors/grey.png",
      "audioUrl": "/audio3/word/color/grey.mp3"
    }, {
      "id": 186,
      "name": "light blue",
      "img": "/img2/colors/light blue.png",
      "audioUrl": "/audio3/word/color/light blue.mp3"
    }, {
      "id": 187,
      "name": "orange",
      "img": "/img2/colors/orange.png",
      "audioUrl": "/audio3/word/color/orange.mp3"
    }]
  }, {
    "id": 15,
    "name": "自然",
    "img": "/daohangtubiao/nature.png",
    "cardList": [{
      "id": 188,
      "name": "cloud",
      "img": "/img2/nature/cloud.png",
      "audioUrl": "/audio3/word/nature/cloud.mp3"
    }, {
      "id": 189,
      "name": "desert",
      "img": "/img2/nature/desert.png",
      "audioUrl": "/audio3/word/nature/desert.mp3"
    }, {
      "id": 190,
      "name": "flower",
      "img": "/img2/nature/flower.png",
      "audioUrl": "/audio3/word/nature/flower.mp3"
    }, {
      "id": 191,
      "name": "frog",
      "img": "/img2/nature/frog.png",
      "audioUrl": "/audio3/word/nature/frog.mp3"
    }, {
      "id": 192,
      "name": "grass",
      "img": "/img2/nature/grass.png",
      "audioUrl": "/audio3/word/nature/grass.mp3"
    }, {
      "id": 193,
      "name": "island",
      "img": "/img2/nature/island.png",
      "audioUrl": "/audio3/word/nature/island.mp3"
    }, {
      "id": 194,
      "name": "lightening",
      "img": "/img2/nature/lightening.png",
      "audioUrl": "/audio3/word/nature/lightening.mp3"
    }, {
      "id": 195,
      "name": "mountain",
      "img": "/img2/nature/mountain.png",
      "audioUrl": "/audio3/word/nature/mountain.mp3"
    }, {
      "id": 196,
      "name": "rain",
      "img": "/img2/nature/rain.png",
      "audioUrl": "/audio3/word/nature/rain.mp3"
    }, {
      "id": 197,
      "name": "rainbow",
      "img": "/img2/nature/rainbow.png",
      "audioUrl": "/audio3/word/nature/rainbow.mp3"
    }, {
      "id": 198,
      "name": "river",
      "img": "/img2/nature/river.png",
      "audioUrl": "/audio3/word/nature/river.mp3"
    }, {
      "id": 199,
      "name": "sea",
      "img": "/img2/nature/sea.png",
      "audioUrl": "/audio3/word/nature/sea.mp3"
    }, {
      "id": 200,
      "name": "sky",
      "img": "/img2/nature/sky.png",
      "audioUrl": "/audio3/word/nature/sky.mp3"
    }, {
      "id": 201,
      "name": "snow",
      "img": "/img2/nature/snow.png",
      "audioUrl": "/audio3/word/nature/snow.mp3"
    }, {
      "id": 202,
      "name": "sun",
      "img": "/img2/nature/sun.png",
      "audioUrl": "/audio3/word/nature/sun.mp3"
    }, {
      "id": 203,
      "name": "thunder",
      "img": "/img2/nature/thunder.png",
      "audioUrl": "/audio3/word/nature/thunder.mp3"
    }, {
      "id": 204,
      "name": "tree",
      "img": "/img2/nature/tree.png",
      "audioUrl": "/audio3/word/nature/tree.mp3"
    }, {
      "id": 205,
      "name": "wind",
      "img": "/img2/nature/wind.png",
      "audioUrl": "/audio3/word/nature/wind.mp3"
    }]
  }, {
    "id": 10,
    "name": "形状",
    "img": "/daohangtubiao/shape.png",
    "cardList": [{
      "id": 103,
      "name": "circle",
      "img": "/img2/shape/circle.png",
      "audioUrl": "/audio3/word/shape/circle.mp3"
    }, {
      "id": 111,
      "name": "diomand",
      "img": "/img2/shape/diamond.png",
      "audioUrl": "/audio3/word/shape/diamond.mp3"
    }, {
      "id": 104,
      "name": "heart",
      "img": "/img2/shape/heart.png",
      "audioUrl": "/audio3/word/shape/heart.mp3"
    }, {
      "id": 105,
      "name": "line",
      "img": "/img2/shape/line.png",
      "audioUrl": "/audio3/word/shape/line.mp3"
    }, {
      "id": 106,
      "name": "oval",
      "img": "/img2/shape/oval.png",
      "audioUrl": "/audio3/word/shape/oval.mp3"
    }, {
      "id": 107,
      "name": "retangle",
      "img": "/img2/shape/rectangle.png",
      "audioUrl": "/audio3/word/shape/retangle.mp3"
    }, {
      "id": 108,
      "name": "square",
      "img": "/img2/shape/square.png",
      "audioUrl": "/audio3/word/shape/square.mp3"
    }, {
      "id": 109,
      "name": "star",
      "img": "/img2/shape/star.png",
      "audioUrl": "/audio3/word/shape/star.mp3"
    }, {
      "id": 110,
      "name": "triangle",
      "img": "/img2/shape/triangle.png",
      "audioUrl": "/audio3/word/shape/triangle.mp3"
    }]
  }]
} as {
  list: CategoryItemEntity[]
};